-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 00:04:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mille_et_une_pousses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mille_et_une_pousses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mille_et_une_pousses` DEFAULT CHARACTER SET utf8 ;
USE `mille_et_une_pousses` ;

-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street_number` INT NOT NULL,
  `street_name` VARCHAR(255) NOT NULL,
  `building` VARCHAR(45) NULL,
  `postal_code` VARCHAR(5) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_cities1_idx` (`city_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`article_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`article_comments` (
  `customer_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`customer_id`, `article_id`),
  INDEX `fk_articles_has_customers_customers1_idx` (`customer_id` ASC),
  INDEX `fk_articles_has_customers_articles1_idx` (`article_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`article_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`article_images` (
  `id` INT NOT NULL,
  `path` TEXT NOT NULL,
  `alt` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`blog_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`blog_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `author_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_customers1_idx` (`author_id` ASC),
  INDEX `fk_articles_images1_idx` (`image_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_countries_idx` (`country_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `salt` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `first_address_id` INT NULL,
  `second_address_id` INT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customers_addresses1_idx` (`first_address_id` ASC),
  INDEX `fk_customers_addresses2_idx` (`second_address_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  INDEX `fk_customers_roles1_idx` (`role_id` ASC),
  UNIQUE INDEX `salt_UNIQUE` (`salt` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_orders_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_orders_has_products_orders1_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NOT NULL,
  `customer_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`product_category` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_categories_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_categories_has_products_categories1_idx` (`category_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`product_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`product_comments` (
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `note` INT NOT NULL,
  `comment` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`customer_id`, `product_id`),
  INDEX `fk_customers_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_customers_has_products_customers1_idx` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` TEXT NOT NULL,
  `alt` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products1_idx` (`product_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` TEXT NOT NULL,
  `vendor_id` INT NOT NULL,
  `options` VARCHAR(55) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_vendors1_idx` (`vendor_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `activation_date` DATE NOT NULL,
  `expiration_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscriptions_orders1_idx` (`order_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mille_et_une_pousses`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mille_et_une_pousses`.`vendors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
